//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asistanMemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Konusma
    {
        public int Konusma_ID { get; set; }
        public string Konusma_Kayit { get; set; }
        public Nullable<System.DateTime> Konusma_Tarih { get; set; }
        public string Konusma_Baslik { get; set; }
    }
}
