//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asistanMemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Not
    {
        public int Not_ID { get; set; }
        public string Not_Baslik { get; set; }
        public string Not_Yazi { get; set; }
        public Nullable<System.DateTime> Not_Tarih { get; set; }
    }
}
